# Generated by Django 3.0.2 on 2020-05-14 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_id', models.FloatField(max_length=1000, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('alias', models.CharField(max_length=1000)),
                ('IATA_airline', models.CharField(max_length=1000)),
                ('ICAO_airline', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=1000)),
                ('city', models.CharField(max_length=1000)),
                ('country', models.CharField(max_length=1000)),
                ('IATA_airport', models.CharField(max_length=1000)),
                ('ICAO_airport', models.CharField(max_length=1000)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('altitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=1000, primary_key=True, serialize=False)),
                ('iso_code', models.CharField(max_length=1000)),
                ('dafif_code', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_voyage', models.IntegerField(default=0)),
                ('email_client', models.EmailField(max_length=40)),
                ('categorie', models.CharField(max_length=40)),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_voyage', models.IntegerField(default=0)),
                ('mail_client', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=40)),
                ('number', models.IntegerField(default=0)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=1000)),
                ('departure_city', models.CharField(max_length=1000)),
                ('departure_airport', models.CharField(max_length=1000)),
                ('arrival_city', models.CharField(max_length=1000)),
                ('arrival_airport', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Voyages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compagnie', models.CharField(max_length=1000)),
                ('ville_depart', models.CharField(max_length=1000)),
                ('aeroport_depart', models.CharField(max_length=1000)),
                ('ville_arrive', models.CharField(max_length=1000)),
                ('aeroport_arrive', models.CharField(max_length=1000)),
                ('date', models.DateField(max_length=1000)),
                ('price', models.IntegerField(default=0)),
                ('places', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airport', models.CharField(max_length=1000)),
                ('destination_airport', models.CharField(max_length=1000)),
                ('stops', models.CharField(max_length=1000)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero.Airlines')),
                ('destination_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aero.Airports')),
                ('source_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aero.Airports')),
            ],
            options={
                'unique_together': {('airline_id', 'source_airport_id', 'destination_airport_id')},
            },
        ),
    ]
