# Generated by Django 3.0.4 on 2020-03-27 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('registration_number', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('amateur_built', models.CharField(max_length=60)),
                ('make', models.CharField(max_length=60)),
                ('model', models.CharField(max_length=60)),
                ('damage', models.CharField(max_length=60)),
                ('nb_of_engines', models.IntegerField(default=0)),
                ('engines_type', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Airlines',
            fields=[
                ('airline_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=40)),
                ('alias', models.CharField(max_length=40)),
                ('IATA_airline', models.CharField(max_length=8)),
                ('ICAO_airline', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Airports',
            fields=[
                ('airport_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('IATA_airport', models.CharField(max_length=8)),
                ('ICAO_airport', models.CharField(max_length=8)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('altitude', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('iso_code', models.CharField(max_length=2)),
                ('dafif_code', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Injuries',
            fields=[
                ('acc_num', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('total_fatal_injuries', models.IntegerField(default=0)),
                ('total_serious_injuries', models.IntegerField(default=0)),
                ('total_minor_injuries', models.IntegerField(default=0)),
                ('total_uninjured', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('acc_num', models.CharField(max_length=60, primary_key=True, serialize=False)),
                ('location', models.CharField(max_length=60)),
                ('country', models.CharField(max_length=60)),
                ('latitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('longitude', models.DecimalField(decimal_places=10, max_digits=13)),
                ('airport_code', models.CharField(max_length=60)),
                ('airport_name', models.CharField(max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('date_event', models.DateField()),
                ('investigation_type', models.CharField(max_length=60)),
                ('injury_severity', models.CharField(max_length=60)),
                ('accident_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero.Location')),
                ('registration_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero.Aircraft')),
            ],
        ),
        migrations.CreateModel(
            name='Routes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_airport', models.CharField(max_length=40)),
                ('destination_airport', models.CharField(max_length=40)),
                ('stops', models.IntegerField(default=0)),
                ('airline_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero.Airlines')),
                ('destination_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aero.Airports')),
                ('source_airport_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aero.Airports')),
            ],
            options={
                'unique_together': {('airline_id', 'source_airport_id', 'destination_airport_id')},
            },
        ),
    ]
