# Generated by Django 3.0.4 on 2020-03-31 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='nb_of_engines',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airline_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airports',
            name='airport_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airports',
            name='latitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='airports',
            name='longitude',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_fatal_injuries',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_minor_injuries',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_serious_injuries',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_uninjured',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.CharField(max_length=35),
        ),
        migrations.AlterField(
            model_name='routes',
            name='stops',
            field=models.CharField(max_length=3),
        ),
    ]
