# Generated by Django 3.0.4 on 2020-04-02 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0003_auto_20200401_0125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='nb_of_engines',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='airlines',
            name='airline_id',
            field=models.FloatField(max_length=1000, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airports',
            name='airport_id',
            field=models.FloatField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='airports',
            name='altitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airports',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='airports',
            name='longitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='event',
            name='date_event',
            field=models.DateField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_fatal_injuries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_minor_injuries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_serious_injuries',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='injuries',
            name='total_uninjured',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='latitude',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='location',
            name='longitude',
            field=models.FloatField(),
        ),
    ]
