# Generated by Django 3.0.4 on 2020-04-02 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0005_event_aircraft_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='nb_of_engines',
            field=models.FloatField(),
        ),
    ]
