# Generated by Django 3.0.4 on 2020-04-10 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0006_auto_20200402_1354'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=25)),
                ('source', models.CharField(max_length=40)),
                ('destination', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Personnels',
            fields=[
                ('nom_utilisateur', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=40)),
                ('prenom', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=40)),
                ('telephone', models.CharField(max_length=25)),
                ('mot_de_passe', models.CharField(max_length=40)),
            ],
        ),
        migrations.AlterField(
            model_name='airports',
            name='airport_id',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
