# Generated by Django 3.0.4 on 2020-04-10 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0007_auto_20200410_1720'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personnels',
            old_name='nom_utilisateur',
            new_name='username',
        ),
    ]
