# Generated by Django 3.0.4 on 2020-04-14 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0008_auto_20200410_1750'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routes',
            unique_together=set(),
        ),
    ]
