# Generated by Django 3.0.4 on 2020-04-14 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0009_auto_20200414_1941'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routes',
            unique_together={('airline_id', 'source_airport_id', 'destination_airport_id')},
        ),
    ]
