# Generated by Django 3.0.4 on 2020-04-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0014_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
    ]
