# Generated by Django 3.0.4 on 2020-04-14 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0018_clients'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reservation',
        ),
        migrations.DeleteModel(
            name='Vols',
        ),
        migrations.DeleteModel(
            name='Voyages',
        ),
    ]
