# Generated by Django 3.0.4 on 2020-04-14 23:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0020_vols'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vols',
        ),
    ]
