# Generated by Django 3.0.4 on 2020-04-15 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0022_reservation_vols_voyages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vols',
        ),
    ]
