# Generated by Django 3.0.4 on 2020-04-15 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0023_delete_vols'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airline', models.CharField(max_length=1000)),
                ('departure_city', models.CharField(max_length=1000)),
                ('departure_airport', models.CharField(max_length=1000)),
                ('arrival_city', models.CharField(max_length=1000)),
                ('arrival_airport', models.CharField(max_length=1000)),
            ],
        ),
        migrations.DeleteModel(
            name='Voyages',
        ),
    ]
