# Generated by Django 3.0.4 on 2020-04-17 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0025_voyages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
