# Generated by Django 3.0.4 on 2020-04-17 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0026_auto_20200417_1919'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_voyage', models.IntegerField(default=0)),
                ('mail_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='aero.Clients')),
            ],
        ),
    ]
