# Generated by Django 3.0.4 on 2020-04-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0027_clients_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='mail_client',
        ),
        migrations.DeleteModel(
            name='Clients',
        ),
        migrations.DeleteModel(
            name='Reservation',
        ),
    ]
