# Generated by Django 3.0.4 on 2020-04-17 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0028_auto_20200417_2227'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=40)),
                ('nationality', models.CharField(max_length=40)),
                ('tel', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_voyage', models.IntegerField(default=0)),
                ('mail_client', models.EmailField(default='', max_length=254)),
            ],
        ),
    ]
