# Generated by Django 3.0.4 on 2020-04-19 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0029_clients_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='accident_number',
        ),
        migrations.RemoveField(
            model_name='event',
            name='registration_number',
        ),
        migrations.DeleteModel(
            name='Injuries',
        ),
        migrations.DeleteModel(
            name='Aircraft',
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
