# Generated by Django 3.0.4 on 2020-04-28 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0030_auto_20200419_1154'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref_voyage', models.IntegerField(default=0)),
                ('email_client', models.EmailField(max_length=40)),
                ('categorie', models.CharField(max_length=40)),
                ('message', models.TextField()),
            ],
        ),
    ]
