# Generated by Django 3.0.4 on 2020-04-28 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0031_reclamation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Voyages',
        ),
    ]
