# Generated by Django 3.0.4 on 2020-05-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aero', '0033_voyages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_pays', models.CharField(max_length=40)),
                ('img', models.CharField(max_length=40)),
                ('number', models.IntegerField(max_length=40)),
                ('percentage', models.IntegerField(default=0)),
            ],
        ),
    ]
